### ISSUE TITLE
KefirJS and WebSockets

### ISSUE THREAD

**Issue by antonioaguilar** [kefirjs/kefir#276] opened 2018-03-14 17:34 UTC
I'm interested to know how to wrap a WebSocket connection as a KefirJS stream and therefore be able to subscribe and publish data to it.  There are many examples of how this could be done in RxJS (via Subjects, or a combination of Observables and Observer). Are there any patterns that can be used within KefirJS to implement this? I appreciate any suggestions.

**Comment by mAAdhaTTah** [comment] 2018-03-14 17:36
Loosely speaking:

```js
const socket$ = Kefir.stream(emitter => {
  const socket = createSocket();
  socket.on('event', e => emitter.value(e));
  return () => socket.close();
});
```

**Comment by AgentME** [comment] 2018-03-14 17:52
Kefir observables generally shouldn't be thought of as objects supporting both read and write operations. Think of the Kefir observable as just representing the read side.

I frequently do things like this:

```js
class WebSocketConnection {
  constructor(createSocket) {
    this._socket = socket;
    this.stream = Kefir.stream(emitter => {
      socket.on('data', e => emitter.value(e));
      socket.on('end', () => emitter.end());
    });
  }

  write(value) {
    this._socket.write(value);
  }

  close() {
    this._socket.close();
  }
}

const wsc = new WebSocketConnection(() => ...);
wsc.stream
  .filter(value => value.type === 'bar')
  .onValue(value => {
    console.log('got bar event', value);
    console.log('responding');
    wsc.write({type: foo, data: value.data + 1});
  });
```

Note a small difference between @mAAdhaTTah and my code: his closes the socket when no one is listening. Depending on your use-case, that may be what you want. But if you don't always have listeners (generally in a very idiomatic reactive codebase you set up a bunch of listeners at the start that stick around, but if you're just using Kefir here and there in a more classic object-oriented codebase that may not be the case) and still want to write to the connection at any time, then you may not want to automatically close it in that case and instead want an explicit close method like here.

**Comment by mAAdhaTTah** [comment] 2018-03-14 19:03
I'm going to close this issue, since it's not a bug, but feel free to ask follow-up questions!

**Closed by mAAdhaTTah** 2018-03-14 19:03 UTC
Labels: question

**Comment by amireldor** [comment] 2020-07-21 21:05
I know this is long closed, but I found that the following code also works and I felt it's too cool not to share.
```
// I imported fromEvents directly from 'kefir'
let myWsStream = fromEvents(websocket, 'message')
```
